print("Milage Calculator")
mile = input("How many miles did you drive?\n")
gallon = input("How many gallons of gas did you use?\n")
milage = float(mile)/float(gallon)
print("Your car gets "+ str(milage) +" per gallon.")
